version: '3.8'

services:
  web:
    build: .
    env_file: .env
    ports:
      - '5000:5000'
    volumes:
      - ./:/app:cached
      - uploads:/app/uploads
      - quarantine:/app/quarantine
    depends_on:
      - clamav
      - minio
    restart: unless-stopped

  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    ports:
      - '3310:3310'
    volumes:
      - clamav-db:/var/lib/clamav
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  uploads:
  quarantine:
  clamav-db:
  minio-data:
